import { createDefaultState, normalizeState, normalizeItem, buildForecast, summarizeForecast, addMonths, exportState, importState, formatCents, SAMPLE_ITEMS, STORAGE_KEY, MAX_STATE_BYTES, MAX_ITEMS, MAX_CENTS, MAX_MONTH_ENTRIES, canAddMonthEntry, setMonthEntry, heightClass } from './app-core.js';

let state = loadState();
const $ = id => document.getElementById(id);
const monthName = new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' });
const monthDate = month => new Date(`${month}-01T00:00:00Z`);
function loadState() { try { const raw = localStorage.getItem(STORAGE_KEY) || localStorage.getItem('balanceahead.state.v1'); return raw ? (importState(raw) || createDefaultState()) : createDefaultState(); } catch { return createDefaultState(); } }
function announce(message, error = false) { $('liveRegion').textContent = message; $('statusRegion').textContent = message; $('statusRegion').className = error ? 'status-region is-error' : 'status-region is-success'; }
function saveState() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); return true; } catch { announce('Your plan could not be saved. Check browser storage and try again.', true); return false; } }
function cents(value) { const number = Number(value); return Number.isFinite(number) ? Math.round(number * 100) : NaN; }
function monthStarting() { return state.startingBalances[state.month] ?? 0; }
function render() {
  $('monthLabel').textContent = monthName.format(monthDate(state.month)); $('startingBalance').value = (monthStarting() / 100).toFixed(2); $('safetyBuffer').value = (state.safetyBufferCents / 100).toFixed(2); $('currency').value = state.currency; $('sampleButton').disabled = state.items.length > 0; $('sampleButton').textContent = state.items.length > 0 ? 'Example plan already added' : 'See an example plan';
  const symbol = formatCents(0, state.currency).replace(/[\d\s.,-]/g, '') || state.currency; document.querySelectorAll('.currency-symbol').forEach(el => el.textContent = symbol);
  const forecast = buildForecast(state); const summary = summarizeForecast(forecast, state.safetyBufferCents); $('lowestBalance').textContent = formatCents(summary.lowestBalanceCents, state.currency); $('monthEndBalance').textContent = formatCents(summary.monthEndBalanceCents, state.currency); $('bufferValue').textContent = formatCents(state.safetyBufferCents, state.currency); $('lowestHint').textContent = summary.warningLevel === 'safe' ? 'Above your buffer' : 'Needs a closer look';
  $('warningBanner').hidden = summary.warningLevel === 'safe'; if (!$('warningBanner').hidden) { $('warningTitle').textContent = summary.warningLevel === 'critical' ? 'Your balance may go below zero.' : 'Your balance may dip below your buffer.'; $('warningText').textContent = `The lowest point is ${formatCents(summary.lowestBalanceCents, state.currency)}. Review the timeline before the month begins.`; }
  renderTimeline(); renderForecast(forecast); saveState();
}
function renderTimeline() { const timeline = $('timeline'); timeline.replaceChildren(); const groups = state.items.filter(item => item.recurrence === 'monthly' ? state.month >= item.createdMonth : state.month === item.createdMonth).reduce((map, item) => { const day = Math.min(item.day, new Date(Date.UTC(Number(state.month.slice(0,4)), Number(state.month.slice(5), 10), 0)).getUTCDate()); (map[day] ??= []).push(item); return map; }, {}); const days = Object.keys(groups).map(Number).sort((a,b)=>a-b); if (!days.length) { timeline.innerHTML = '<div class="empty-state"><strong>Your timeline is ready for its first item.</strong><span>Add income or bills, or try the example plan to see how it works.</span></div>'; return; } days.forEach(day => { const dayEl=document.createElement('div'); dayEl.className='timeline-day'; const label=document.createElement('div'); label.className='day-number'; label.textContent=`Day ${day}`; const events=document.createElement('div'); events.className='day-events'; groups[day].forEach(item => { const row=document.createElement('div'); row.className='timeline-item'; const main=document.createElement('div'); main.className='item-main'; const name=document.createElement('div'); name.className='item-name'; name.textContent=item.name; if (item.statusByMonth?.[state.month] === 'paid') { const pill=document.createElement('span'); pill.className='status-pill'; pill.textContent=item.type==='income'?'Received':'Paid'; name.append(pill); } const meta=document.createElement('div'); meta.className='item-meta'; meta.textContent=`${item.type==='income'?'Income':'Bill'} · ${item.recurrence==='monthly'?'monthly':'one-time'}`; main.append(name,meta); const amount=document.createElement('strong'); amount.className=`item-amount ${item.type}`; amount.textContent=`${item.type==='income'?'+':'−'}${formatCents(item.amountCents,state.currency)}`; const actions=document.createElement('div'); actions.className='item-actions'; const status=document.createElement('button'); status.className='mini-button'; status.type='button'; status.textContent=item.statusByMonth?.[state.month]==='paid'?'Mark pending':item.type==='income'?'Mark received':'Mark paid'; status.setAttribute('aria-label',`${status.textContent}: ${item.name}`); status.onclick=()=>toggleStatus(item.id); const edit=document.createElement('button'); edit.className='mini-button'; edit.type='button'; edit.textContent='Edit'; edit.setAttribute('aria-label',`Edit ${item.name}`); edit.onclick=()=>openItem(item); const remove=document.createElement('button'); remove.className='mini-button'; remove.type='button'; remove.textContent='Delete'; remove.setAttribute('aria-label',`Delete ${item.name}`); remove.onclick=()=>deleteItem(item.id); actions.append(status,edit,remove); row.append(main,amount,actions); events.append(row); }); dayEl.append(label,events); timeline.append(dayEl); }); }
function renderForecast(forecast) { const chart=$('forecastChart'); chart.replaceChildren(); const startLabel=document.createElement('span'); startLabel.className='chart-endpoint chart-start'; startLabel.textContent='Day 1'; const endLabel=document.createElement('span'); endLabel.className='chart-endpoint chart-end'; endLabel.textContent='Month end'; chart.append(startLabel); const values=forecast.map(day=>day.balanceCents); const min=Math.min(0,...values); const max=Math.max(...values,state.safetyBufferCents,1); const range=max-min||1; forecast.forEach(day=>{ const bar=document.createElement('div'); bar.className='forecast-bar'+(day.balanceCents<0?' is-negative':day.balanceCents<state.safetyBufferCents?' is-warning':''); bar.title=`Day ${day.day}: ${formatCents(day.balanceCents,state.currency)}`; const fill=document.createElement('span'); fill.className=heightClass(((day.balanceCents-min)/range)*100); bar.append(fill); chart.append(bar); }); chart.append(endLabel); const table=$('forecastTableBody'); table.replaceChildren(); forecast.forEach(day=>{ const row=document.createElement('tr'); const status=day.balanceCents<0?'negative':day.balanceCents<state.safetyBufferCents?'below buffer':'above buffer'; [day.day,formatCents(day.balanceCents,state.currency),status].forEach(value=>{const cell=document.createElement('td');cell.textContent=value;row.append(cell);}); table.append(row); }); }
function openItem(item=null) { document.querySelectorAll('#itemForm [aria-invalid]').forEach(field => field.setAttribute('aria-invalid','false')); $('dialogTitle').textContent=item?'Edit an item':'Add an item'; $('editingId').value=item?.id||''; $('itemType').value=item?.type||'income'; $('itemName').value=item?.name||''; $('itemAmount').value=item?(item.amountCents/100).toFixed(2):''; $('itemDay').value=item?.day||''; $('itemRecurrence').value=item?.recurrence||'monthly'; $('itemDialog').showModal(); $('itemName').focus(); }
function toggleStatus(id) { const item=state.items.find(entry=>entry.id===id); if(!item)return; if(!Object.prototype.hasOwnProperty.call(item.statusByMonth,state.month) && !canAddMonthEntry(item.statusByMonth,state.month)) return announce(`This item has reached the ${MAX_MONTH_ENTRIES}-month status limit.`,true); item.statusByMonth=setMonthEntry(item.statusByMonth,state.month,item.statusByMonth?.[state.month]==='paid'?'pending':'paid'); render(); announce(`${item.name} marked ${item.statusByMonth[state.month] === 'paid' ? item.type==='income'?'received':'paid':'pending'}.`); }
function deleteItem(id) { const item=state.items.find(entry=>entry.id===id); if(!item||!window.confirm(`Delete ${item.name}?`))return; state.items=state.items.filter(entry=>entry.id!==id); render(); announce(`${item.name} deleted.`); }
$('saveSetup').onclick=()=>{ const starting=cents($('startingBalance').value), buffer=cents($('safetyBuffer').value); $('startingBalance').setAttribute('aria-invalid','false'); $('safetyBuffer').setAttribute('aria-invalid','false'); if(!Number.isSafeInteger(starting)||Math.abs(starting)>MAX_CENTS||!Number.isSafeInteger(buffer)||buffer<0||buffer>MAX_CENTS){ if(!Number.isSafeInteger(starting)||Math.abs(starting)>MAX_CENTS)$('startingBalance').setAttribute('aria-invalid','true'); if(!Number.isSafeInteger(buffer)||buffer<0||buffer>MAX_CENTS)$('safetyBuffer').setAttribute('aria-invalid','true'); const firstInvalid=document.querySelector('#setupCard [aria-invalid="true"]'); firstInvalid?.focus(); announce(`Enter a starting balance between −${MAX_CENTS/100} and ${MAX_CENTS/100}, and a non-negative safety buffer within that limit.`,true); return; } if(!canAddMonthEntry(state.startingBalances,state.month)) return announce(`Your plan has reached the ${MAX_MONTH_ENTRIES}-month limit. Remove an older month before saving this starting point.`,true); state.startingBalances=setMonthEntry(state.startingBalances,state.month,starting); state.safetyBufferCents=buffer; state.currency=$('currency').value; render(); announce('Starting point saved. Currency changes symbols only; no conversion is performed.'); };
$('addItemButton').onclick=()=>state.items.length>=MAX_ITEMS?announce(`You have reached the ${MAX_ITEMS}-item limit. Delete an item before adding another.`,true):openItem();
$('itemForm').addEventListener('submit',event=>{ event.preventDefault(); const existing=state.items.find(entry=>entry.id===$('editingId').value); const item=normalizeItem({id:$('editingId').value,type:$('itemType').value,name:$('itemName').value,amountCents:cents($('itemAmount').value),day:Number($('itemDay').value),recurrence:$('itemRecurrence').value,createdMonth:existing?.createdMonth||state.month,statusByMonth:existing?.statusByMonth||{}} ,state.month); if(!item){ ['itemName','itemAmount','itemDay'].forEach(id=>$(id).setAttribute('aria-invalid','false')); const fields=[['itemName',!$('itemName').value.trim()],['itemAmount',!Number.isFinite(cents($('itemAmount').value))||cents($('itemAmount').value)<=0],['itemDay',!Number.isInteger(Number($('itemDay').value))||Number($('itemDay').value)<1||Number($('itemDay').value)>31]]; fields.forEach(([id,bad])=>{if(bad)$(id).setAttribute('aria-invalid','true');}); const firstInvalid=document.querySelector('#itemForm [aria-invalid="true"]'); firstInvalid?.focus(); announce('Please enter a valid name, positive amount, and day from 1 to 31.',true); return; } const index=state.items.findIndex(entry=>entry.id===item.id); if(index>=0)state.items[index]={...state.items[index],...item}; else if(state.items.length<MAX_ITEMS)state.items.push(item); else return announce(`You have reached the ${MAX_ITEMS}-item limit.`,true); $('itemDialog').close(); render(); announce(`${item.name} saved.`); });
$('previousMonth').onclick=()=>{state.month=addMonths(state.month,-1);render();announce(`Showing ${monthName.format(monthDate(state.month))}.`);}; $('nextMonth').onclick=()=>{state.month=addMonths(state.month,1);render();announce(`Showing ${monthName.format(monthDate(state.month))}.`);}; $('sampleButton').onclick=()=>{if(state.items.length)return announce('Your existing timeline was kept. Example data is only added to an empty timeline.'); state.items=SAMPLE_ITEMS.map(item=>({...item,createdMonth:state.month}));render();announce('Example plan added.');};
$('exportButton').onclick=()=>{try{const blob=new Blob([exportState(state)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`balanceahead-${state.month}.json`;link.click();URL.revokeObjectURL(url);announce('Private backup downloaded.');}catch{announce('Your plan could not be exported because its bounded state is invalid. Your data was not replaced.',true);}};
$('importFile').onchange=async event=>{const file=event.target.files[0];if(!file)return;if(file.size>MAX_STATE_BYTES){announce('That backup is too large to import. Your current plan is unchanged.',true);return;}try{const imported=importState(await file.text());if(!imported){announce('That backup is invalid or from an unsupported version. Your current plan is unchanged.',true);return;}state=imported;render();announce('Backup imported.');}catch{announce('That backup could not be read. Your current plan is unchanged.',true);}event.target.value='';};
$('clearButton').onclick=()=>{if(!window.confirm('Clear this entire plan? This cannot be undone unless you exported a backup.'))return;state=createDefaultState(state.month);render();announce('All plan data cleared.');}; $('printButton').onclick=()=>window.print(); $('privacyButton').onclick=()=>$('privacyDialog').showModal(); $('closePrivacy').onclick=()=>$('privacyDialog').close(); $('privacyDone').onclick=()=>$('privacyDialog').close(); $('closeItem').onclick=()=>$('itemDialog').close(); $('cancelItem').onclick=()=>$('itemDialog').close();
render();
